# Site Settings
baseurl: ""
url : "https://leejaeyeong.github.io"

# Blog Settings
theme_settings :
  title : jylee. blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : jylee.
    description : 생각하는 대로 살지 않으면, <br> 사는 대로 생각하게 된다.
    experience :
      - start : 2019-03-01
        end : 2020-02-29
        experience : 멋쟁이사자처럼 7기 
      - start : 2020-03-01
        end : 2021-02-29
        experience : 멋쟁이사자처럼 8기 운영진 
    skills : 
      - skill : HTML5 & CSS
        value : 80  # Percent value
      - skill : Python & Django 
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: leejaeyeong
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
